#!/usr/bin/with-contenv bash

USER=${USER-helx}

export HOME="/home/$USER"
export CUSTOM_USER="$USER"
PASSWORD=$(sudo -u $USER cat $HOME/.password)
# In some environments (maybe root-squash enabled) root can not write to
# shares, so do some tasks as $USER.
sudo -u $USER rm -f $HOME/.password
export AUTO_LOGIN="true"

PASSWORD=$PASSWORD exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${CUSTOM_PORT:=3000}" \
        cd /gclient s6-setuidgid $USER node app.js
