#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# some code taken from rstudio user init

## Set defaults for environmental variables in case they are undefined
DEFAULT_USER=${DEFAULT_USER:-helx}
USER=${USER:=${DEFAULT_USER}}
USERID=${PUID:=1000}
GROUPID=${PGID:=1000}
UMASK=${UMASK:=022}
LANG=${LANG:=en_US.UTF-8}
TZ=${TZ:=Etc/UTC}

PASSWORD=$(pwgen 16 1)
printf "\n\n"
tput bold
printf "The password is set to \e[31m%s\e[39m\n" "$PASSWORD"
printf "If you want to set your own password, set the PASSWORD environment variable. e.g. run with:\n"
printf "docker run -e PASSWORD=\e[92m<YOUR_PASS>\e[39m -p 8787:8787 rocker/rstudio\n"
tput sgr0
printf "\n\n"

echo "creating new $USER with UID $USERID"
useradd -m "$USER" -s /bin/bash -u $USERID
mkdir -p /home/"$USER"
chown -R "$USER" /home/"$USER"
usermod -a -G staff "$USER"
echo "$PASSWORD">/home/$USER/.password
chmod 600 /home/$USER/.password
ls -al /home/$USER

if [ "$GROUPID" -ne 1000 ]; then
    echo "Modifying primary group $(id "${USER}" -g -n)"
    groupmod -o -g $GROUPID "$(id "${USER}" -g -n)"
    echo "Primary group ID is now custom_group $GROUPID"
fi

## Add a password to user
echo "$USER:$PASSWORD" | chpasswd

## Next one for timezone setup
if [ "$TZ" != "Etc/UTC" ]; then
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
fi

## Update Locale if needed
if [ "$LANG" != "en_US.UTF-8" ]; then
    /usr/sbin/locale-gen --lang $LANG
    /usr/sbin/update-locale --reset LANG=$LANG
fi

PUID=${PUID:-911}
PGID=${PGID:-911}

echo '
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------'
if [[ -f /donate.txt ]]; then
    echo '
To support the app dev(s) visit:'
    cat /donate.txt
fi
echo '
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u $USER)
User gid:    $(id -g $USER)
-------------------------------------
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
    echo '
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Apps will not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
'
    sleep infinity
fi

